//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.Framework.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.Framework.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __ApplicationRestarting.
        /// </summary>
        internal static string ApplicationRestartingKey {
            get {
                return ResourceManager.GetString("ApplicationRestartingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __AuthenticationMode.
        /// </summary>
        internal static string AuthenticationModeKey {
            get {
                return ResourceManager.GetString("AuthenticationModeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must derive from System.MarshlByRefObject..
        /// </summary>
        internal static string CannotMarshalByRef {
            get {
                return ResourceManager.GetString("CannotMarshalByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeMappings.
        /// </summary>
        internal static string ConfiguraitonSectionName {
            get {
                return ResourceManager.GetString("ConfiguraitonSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fail to parse the InstanceBuidler configuration!.
        /// </summary>
        internal static string ConfigurationErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.instanceBuilder.
        /// </summary>
        internal static string ConfigurationSectionGroupName {
            get {
                return ResourceManager.GetString("ConfigurationSectionGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contextItems.
        /// </summary>
        internal static string ContextItemsConfigSectionName {
            get {
                return ResourceManager.GetString("ContextItemsConfigSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.contextPropagation.
        /// </summary>
        internal static string ContextPropagationConfigGroupName {
            get {
                return ResourceManager.GetString("ContextPropagationConfigGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __CredentialCookie.
        /// </summary>
        internal static string CredentialCookieKey {
            get {
                return ResourceManager.GetString("CredentialCookieKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __CurrentCulture.
        /// </summary>
        internal static string CurrentCultureKey {
            get {
                return ResourceManager.GetString("CurrentCultureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration element type {0} does not have an accessible constructor taking a ConnectionStringSettings and an IConfigurationSource as constructor arguments..
        /// </summary>
        internal static string ExceptionDatabaseDataTypeDoesNotHaveRequiredConstructor {
            get {
                return ResourceManager.GetString("ExceptionDatabaseDataTypeDoesNotHaveRequiredConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration element type {0} does not inherit from the DatabaseData class..
        /// </summary>
        internal static string ExceptionDatabaseDataTypeDoesNotInheritFromDatabaseData {
            get {
                return ResourceManager.GetString("ExceptionDatabaseDataTypeDoesNotInheritFromDatabaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The default database is not configured..
        /// </summary>
        internal static string ExceptionDefaultDatabaseNotExists {
            get {
                return ResourceManager.GetString("ExceptionDefaultDatabaseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type &quot;{0}&quot; is not a valid service contract..
        /// </summary>
        internal static string ExceptionInvalidServiceContractType {
            get {
                return ResourceManager.GetString("ExceptionInvalidServiceContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type {0} does not contain the ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionNoConfigurationElementTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration section &quot;connectionStrings&quot; does not exist..
        /// </summary>
        internal static string ExceptionNoConnectionStringSection {
            get {
                return ResourceManager.GetString("ExceptionNoConnectionStringSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The requested database {0} is not defined in configuration..
        /// </summary>
        internal static string ExceptionNoDatabaseDefined {
            get {
                return ResourceManager.GetString("ExceptionNoDatabaseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The requested database {0} does not have provider name set in the connection string..
        /// </summary>
        internal static string ExceptionNoProviderDefinedForConnectionString {
            get {
                return ResourceManager.GetString("ExceptionNoProviderDefinedForConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Auto-Interception only support instance interceptor..
        /// </summary>
        internal static string ExceptionOnlyInstanceInterceptorBeSupported {
            get {
                return ResourceManager.GetString("ExceptionOnlyInstanceInterceptorBeSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The unity container named &quot;{0}&quot; is not configured..
        /// </summary>
        internal static string ExceptionUnityConainerNotExists {
            get {
                return ResourceManager.GetString("ExceptionUnityConainerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __FullName.
        /// </summary>
        internal static string FullNameKey {
            get {
                return ResourceManager.GetString("FullNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __HostName.
        /// </summary>
        internal static string HostNameKey {
            get {
                return ResourceManager.GetString("HostNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&quot; is not a valid qualified type assembly name!.
        /// </summary>
        internal static string InvalidQuanlifiedTypeName {
            get {
                return ResourceManager.GetString("InvalidQuanlifiedTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __IPAddress.
        /// </summary>
        internal static string IPAddressKey {
            get {
                return ResourceManager.GetString("IPAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __LastLoginDate.
        /// </summary>
        internal static string LastLoginDateKey {
            get {
                return ResourceManager.GetString("LastLoginDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __SessionID.
        /// </summary>
        internal static string SessionIDKey {
            get {
                return ResourceManager.GetString("SessionIDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __SessionRefreshInterval.
        /// </summary>
        internal static string SessionRefreshIntervalKey {
            get {
                return ResourceManager.GetString("SessionRefreshIntervalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __SessionTimeoutInterval.
        /// </summary>
        internal static string SessionTimeoutIntervalKey {
            get {
                return ResourceManager.GetString("SessionTimeoutIntervalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __TransactionID.
        /// </summary>
        internal static string TransactionIDKey {
            get {
                return ResourceManager.GetString("TransactionIDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not assignable..
        /// </summary>
        internal static string TypesAreNotAssignable {
            get {
                return ResourceManager.GetString("TypesAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __UserID.
        /// </summary>
        internal static string UserIDKey {
            get {
                return ResourceManager.GetString("UserIDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __UserName.
        /// </summary>
        internal static string UserNameKey {
            get {
                return ResourceManager.GetString("UserNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __UserRoles.
        /// </summary>
        internal static string UserRolesKey {
            get {
                return ResourceManager.GetString("UserRolesKey", resourceCulture);
            }
        }
    }
}
