//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The application did not exist..
        /// </summary>
        internal static string ApplicationNameNotExists {
            get {
                return ResourceManager.GetString("ApplicationNameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The total size of compressed message..
        /// </summary>
        internal static string CompressedMessageSizeCounterHelpResource {
            get {
                return ResourceManager.GetString("CompressedMessageSizeCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The compression duration..
        /// </summary>
        internal static string CompressionElapsedTimeCounterHelpResource {
            get {
                return ResourceManager.GetString("CompressionElapsedTimeCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The record has been updated by others..
        /// </summary>
        internal static string ConcurrentUpdated {
            get {
                return ResourceManager.GetString("ConcurrentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration element whose name is &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ConfiguraitonElementNotExists {
            get {
                return ResourceManager.GetString("ConfiguraitonElementNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The performance counters for iConnect.Core..
        /// </summary>
        internal static string CounterCategoryHelpResourceName {
            get {
                return ResourceManager.GetString("CounterCategoryHelpResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot locate the &quot;{0}&quot; configuration section..
        /// </summary>
        internal static string ExceptionAppContextSettingsNotExists {
            get {
                return ResourceManager.GetString("ExceptionAppContextSettingsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The provided string argument must not be empty..
        /// </summary>
        internal static string ExceptionArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ExceptionArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot change or override the readonly ContextItem..
        /// </summary>
        internal static string ExceptionCannotChangeReadonlyContextItem {
            get {
                return ResourceManager.GetString("ExceptionCannotChangeReadonlyContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot not find a readable &quot;{0}&quot; property for the type &quot;{1}&quot;.
        /// </summary>
        internal static string ExceptionCannotLocateReadableProperty {
            get {
                return ResourceManager.GetString("ExceptionCannotLocateReadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot not find a writable &quot;{0}&quot; property for the type &quot;{1}&quot;.
        /// </summary>
        internal static string ExceptionCannotLocateWriterableProperty {
            get {
                return ResourceManager.GetString("ExceptionCannotLocateWriterableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot modify the extended properties of the readonly ContextItem..
        /// </summary>
        internal static string ExceptionCannotModifyReadonlyProperties {
            get {
                return ResourceManager.GetString("ExceptionCannotModifyReadonlyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot modify the value of the readonly ContextItem..
        /// </summary>
        internal static string ExceptionCannotModifyReadonlyValue {
            get {
                return ResourceManager.GetString("ExceptionCannotModifyReadonlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot resolve the assembly qualified type name &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionCannotResolveTypeName {
            get {
                return ResourceManager.GetString("ExceptionCannotResolveTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ExceptionConfigurationLoadFileNotFound=The configuration file {0} could not be found..
        /// </summary>
        internal static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuraiton section name is not specified by decorating the type &quot;{0}&quot; with a ConfigurationSectionNameAttribute..
        /// </summary>
        internal static string ExceptionConfigurationSectionNameAttributeNotExists {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSectionNameAttributeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  One or more current ContextItem cannot be serialized..
        /// </summary>
        internal static string ExceptionContextCannotBeSerialized {
            get {
                return ResourceManager.GetString("ExceptionContextCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The entry with the culture &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ExceptionCultureNotExists {
            get {
                return ResourceManager.GetString("ExceptionCultureNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You must specify the configuraton name of custom MessageCompressor when you select Custom MessageCompressor..
        /// </summary>
        internal static string ExceptionCustomMessageCompressorNotExists {
            get {
                return ResourceManager.GetString("ExceptionCustomMessageCompressorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The same property name &quot;{0}&quot; is configurated in the entity..
        /// </summary>
        internal static string ExceptionDataPropertyDuplicateName {
            get {
                return ResourceManager.GetString("ExceptionDataPropertyDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The default service locator cannot be activated..
        /// </summary>
        internal static string ExceptionDefaultServiceLocatorNotExists {
            get {
                return ResourceManager.GetString("ExceptionDefaultServiceLocatorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The DefaultCacheStore&apos;s expiration mode is specified &quot;FileDepedency&quot;, but the &quot;DependentFileName&quot; is not specified..
        /// </summary>
        internal static string ExceptionDepedentFileNameNotInitialized {
            get {
                return ResourceManager.GetString("ExceptionDepedentFileNameNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The entry with the culture &quot;{0}&quot; exists..
        /// </summary>
        internal static string ExceptionDuplicateCulture {
            get {
                return ResourceManager.GetString("ExceptionDuplicateCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There must be only one culture neutral entry..
        /// </summary>
        internal static string ExceptionDuplicateNeutralEntry {
            get {
                return ResourceManager.GetString("ExceptionDuplicateNeutralEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The given list or array cannot be null or empty..
        /// </summary>
        internal static string ExceptionEmptyArrayOrList {
            get {
                return ResourceManager.GetString("ExceptionEmptyArrayOrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The given entry has been added into another set..
        /// </summary>
        internal static string ExceptionEntryAddedIntoAnotherSet {
            get {
                return ResourceManager.GetString("ExceptionEntryAddedIntoAnotherSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The given entry has been added into the set..
        /// </summary>
        internal static string ExceptionEntryAddedIntoSet {
            get {
                return ResourceManager.GetString("ExceptionEntryAddedIntoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The given entry is not added into the set..
        /// </summary>
        internal static string ExceptionEntryNotAddedIntoSet {
            get {
                return ResourceManager.GetString("ExceptionEntryNotAddedIntoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The specified expired time can not be parsed as a valid TimeSpan..
        /// </summary>
        internal static string ExceptionExpiredTimeNotValidTimeSpan {
            get {
                return ResourceManager.GetString("ExceptionExpiredTimeNotValidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The backup ContextLocator must not be &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionInvalidBackupLocator {
            get {
                return ResourceManager.GetString("ExceptionInvalidBackupLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invalid cast from type &quot;{0}&quot; to type &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionInvalidCast {
            get {
                return ResourceManager.GetString("ExceptionInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Culture name &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string ExceptionInvalidCultureName {
            get {
                return ResourceManager.GetString("ExceptionInvalidCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot locate the database of &quot;{0}&quot; for the configuration..
        /// </summary>
        internal static string ExceptionInvalidDatabaseName {
            get {
                return ResourceManager.GetString("ExceptionInvalidDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The format length is invalid..
        /// </summary>
        internal static string ExceptionInvalidExtendedFormatArguments {
            get {
                return ResourceManager.GetString("ExceptionInvalidExtendedFormatArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The valid page index must be a positive integer..
        /// </summary>
        internal static string ExceptionInvalidPageIndex {
            get {
                return ResourceManager.GetString("ExceptionInvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The valid page size must be a positive integer..
        /// </summary>
        internal static string ExceptionInvalidPageSize {
            get {
                return ResourceManager.GetString("ExceptionInvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The ApplicationContextScope cannot be created in the same thread in which the context items are cloned..
        /// </summary>
        internal static string ExceptionInvalidThreadToCreateContextScope {
            get {
                return ResourceManager.GetString("ExceptionInvalidThreadToCreateContextScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot load the type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionInvalidTypeAssemblyQualifiedName {
            get {
                return ResourceManager.GetString("ExceptionInvalidTypeAssemblyQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot retrieve property &apos;{0}&apos; because localization failed.  Type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;..
        /// </summary>
        internal static string ExceptionLocalizationFailed {
            get {
                return ResourceManager.GetString("ExceptionLocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The message entry &quot;{0}&quot; cannot be found from the category &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionMessageEntryNotExists {
            get {
                return ResourceManager.GetString("ExceptionMessageEntryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The method just be only implemented in sub classes..
        /// </summary>
        internal static string ExceptionMethodMustBeImplementedBySubclasses {
            get {
                return ResourceManager.GetString("ExceptionMethodMustBeImplementedBySubclasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot locate the configuration section of &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionMissingConfigSection {
            get {
                return ResourceManager.GetString("ExceptionMissingConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration element type is not mapped to the type &quot;{0}&quot; by applying ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionMissingConfigurationElementTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionMissingConfigurationElementTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Container does not have the interception extension..
        /// </summary>
        internal static string ExceptionMustContainInterceptionExtension {
            get {
                return ResourceManager.GetString("ExceptionMustContainInterceptionExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There is no culture neutral entry..
        /// </summary>
        internal static string ExceptionNeutralEntryNotExists {
            get {
                return ResourceManager.GetString("ExceptionNeutralEntryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration element type is not specified by the ConfigurationElementAttribute applied to the type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionNotApplyConfigurationElementAttribute {
            get {
                return ResourceManager.GetString("ExceptionNotApplyConfigurationElementAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The PropertyAccessor&apos;s type cannot be assignable fromThe given object&apos;s type..
        /// </summary>
        internal static string ExceptionNotAssignableFrom {
            get {
                return ResourceManager.GetString("ExceptionNotAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No &quot;{0}&quot; can be resolved from deployed assemblies..
        /// </summary>
        internal static string ExceptionNotDeployComponent {
            get {
                return ResourceManager.GetString("ExceptionNotDeployComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The delegate {0} is not a valid event handler..
        /// </summary>
        internal static string ExceptionNotEventHandler {
            get {
                return ResourceManager.GetString("ExceptionNotEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The CompressionEndpointBehavice can only be applied SOAP based endpoint ..
        /// </summary>
        internal static string ExceptionNotSoapMessage {
            get {
                return ResourceManager.GetString("ExceptionNotSoapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The  type of the configuration section of &quot;{0}&quot; is not &quot;1&quot;..
        /// </summary>
        internal static string ExceptionNotSpeciifedConfigSection {
            get {
                return ResourceManager.GetString("ExceptionNotSpeciifedConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The property &quot;{0}&quot; is not defined in the type &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionPropertyNotExists {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The property &quot;{0}&quot; of the type &quot;{1}&quot; is not readable..
        /// </summary>
        internal static string ExceptionPropertyNotReadable {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The property &quot;{0}&quot; of the type &quot;{1}&quot; is not writable..
        /// </summary>
        internal static string ExceptionPropertyNotWritable {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day of Week in Extended Format out of range..
        /// </summary>
        internal static string ExceptionRangeDay {
            get {
                return ResourceManager.GetString("ExceptionRangeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hour in Extended Format out of range..
        /// </summary>
        internal static string ExceptionRangeHour {
            get {
                return ResourceManager.GetString("ExceptionRangeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minutes in Extended Format out of range..
        /// </summary>
        internal static string ExceptionRangeMinute {
            get {
                return ResourceManager.GetString("ExceptionRangeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Month of Year in Extended Format out of range..
        /// </summary>
        internal static string ExceptionRangeMonth {
            get {
                return ResourceManager.GetString("ExceptionRangeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There is no element in the sequence..
        /// </summary>
        internal static string ExceptionSequenceNoElement {
            get {
                return ResourceManager.GetString("ExceptionSequenceNoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The service locator &quot;{0}&quot; is not configured..
        /// </summary>
        internal static string ExceptionServiceLocatorNotExists {
            get {
                return ResourceManager.GetString("ExceptionServiceLocatorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The configuration section &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ExceptionSettingsNotExists {
            get {
                return ResourceManager.GetString("ExceptionSettingsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The setting source &quot;{0}&quot; is not configured..
        /// </summary>
        internal static string ExceptionSettingSourceNotExists {
            get {
                return ResourceManager.GetString("ExceptionSettingSourceNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TransformContext is not initialized..
        /// </summary>
        internal static string ExceptionTransformContextNotInitialized {
            get {
                return ResourceManager.GetString("ExceptionTransformContextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Transient call interception can only be used for non-generic interface..
        /// </summary>
        internal static string ExceptionTransientCallInterceptOnlyForNonGenericInterface {
            get {
                return ResourceManager.GetString("ExceptionTransientCallInterceptOnlyForNonGenericInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The message entry &quot;{0}&quot; (culture=&quot;{1}&quot;) cannot be found from the category &quot;{2}&quot;..
        /// </summary>
        internal static string ExceptionTranslationEntryNotExists {
            get {
                return ResourceManager.GetString("ExceptionTranslationEntryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Custom Service Locator &apos;{0}&apos; with Type &apos;{1}&apos; must derive from IServiceLocator..
        /// </summary>
        internal static string ExceptionTypeForCustomServiceLocatorMustDeriveFrom {
            get {
                return ResourceManager.GetString("ExceptionTypeForCustomServiceLocatorMustDeriveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type &quot;{0}&quot; does not have default construtor..
        /// </summary>
        internal static string ExceptionTypeHasNoContructor {
            get {
                return ResourceManager.GetString("ExceptionTypeHasNoContructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Type of the service location context cannot be be..
        /// </summary>
        internal static string ExceptionTypeofContextCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionTypeofContextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type {1} cannot be assigned to variables of type {0}..
        /// </summary>
        internal static string ExceptionTypesAreNotAssignable {
            get {
                return ResourceManager.GetString("ExceptionTypesAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot locate the unity configuration section for the current configuration source..
        /// </summary>
        internal static string ExceptionUnityConfigSectionNotExists {
            get {
                return ResourceManager.GetString("ExceptionUnityConfigSectionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The unity container &quot;{0}&quot; specified does not exist..
        /// </summary>
        internal static string ExceptionUnityContainerNotExists {
            get {
                return ResourceManager.GetString("ExceptionUnityContainerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;unknown&gt;.
        /// </summary>
        internal static string ExceptionUnknownType {
            get {
                return ResourceManager.GetString("ExceptionUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type {0} is not interceptable for Transient Call..
        /// </summary>
        internal static string InterceptionNotSupportedForTransientCall {
            get {
                return ResourceManager.GetString("InterceptionNotSupportedForTransientCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The total size of source message..
        /// </summary>
        internal static string SourceMessageSizeCounterHelpResource {
            get {
                return ResourceManager.GetString("SourceMessageSizeCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The total times of compression attempts..
        /// </summary>
        internal static string TotalCompressionAttemptsHelpResource {
            get {
                return ResourceManager.GetString("TotalCompressionAttemptsHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The total times of compression..
        /// </summary>
        internal static string TotalCompressionHitsCounterHelpResource {
            get {
                return ResourceManager.GetString("TotalCompressionHitsCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The total times of missing compression ..
        /// </summary>
        internal static string TotoalCompressionMissesCounterHelpResource {
            get {
                return ResourceManager.GetString("TotoalCompressionMissesCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Transaction already completed..
        /// </summary>
        internal static string TransactionAlreadyCompleted {
            get {
                return ResourceManager.GetString("TransactionAlreadyCompleted", resourceCulture);
            }
        }
    }
}
